name: CI

on:
  push:
  pull_request:

jobs:
  test:
    uses: waoooolab/openwaoooo/.github/workflows/service-python-ci-reusable.yml@0b3ff9b6ba8762600c275df0d35dee4bc81c7d0a
    with:
      own_package: device_hub
      install_command: |
        python -m pip install --upgrade pip
        python -m pip install -e .
      test_command: |
        python scripts/run_tests.py
